config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'flights#index'
  resources :flights, only: :index
  resources :bookings, only: [:new, :create, :show, :index] do
    get 'search', on: :collection
  end
  
  get 'about', to: 'application#about'
end

app/models/airport.rb
# == Schema Information
#
# Table name: airports
#
#  id         :bigint           not null, primary key
#  code       :string           not null
#  name       :string           not null
#  city       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Airport < ApplicationRecord
  has_many :departing_flights,
    class_name: :Flight,
    foreign_key: :origin_id,
    dependent: :destroy

  has_many :arriving_flights,
    class_name: :Flight,
    foreign_key: :destination_id,
    dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
# == Schema Information
#
# Table name: bookings
#
#  id           :bigint           not null, primary key
#  flight_id    :bigint           not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  confirmation :string           not null
#
class Booking < ApplicationRecord
  belongs_to :flight
  has_many :passenger_bookings, dependent: :delete_all
  has_many :passengers, through: :passenger_bookings, inverse_of: :bookings

  accepts_nested_attributes_for :passengers

  before_validation :find_or_create_passenger
  before_save :ensure_confirmation

  def to_param
    confirmation
  end

  private

  def find_or_create_passenger
    self.passengers = self.passengers.map do |passenger|
      Passenger.find_or_create_by(email: passenger.email, name: passenger.name)
    end
  end

  def ensure_confirmation
    return if confirmation

    loop do
      self.confirmation = generate_confirmation_number
      break unless self.class.where(confirmation: confirmation).exists?
    end
  end

  def generate_confirmation_number(size = 6)
    charset = %w{ A C D E F G H J K M N P Q R T V W X Y Z }
    (0...size).map{ charset.to_a[rand(charset.size)] }.join
  end
end

app/models/flight.rb
# == Schema Information
#
# Table name: flights
#
#  id             :bigint           not null, primary key
#  duration       :integer          not null
#  origin_id      :bigint           not null
#  destination_id :bigint           not null
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  date           :date             not null
#  time           :time             not null
#  flight_number  :integer          default(-1), not null
#
class Flight < ApplicationRecord
  def self.reset_all_flight_numbers!
    self.all.each { |flight| flight.reset_flight_number! }
  end

  attr_accessor :tickets

  belongs_to :origin, class_name: :Airport
  belongs_to :destination, class_name: :Airport
  has_many :bookings
  has_many :passengers, through: :bookings

  def formatted_date
    date.strftime("%m/%d/%Y")
  end

  def formatted_time
    time.strftime('%l:%M%P')
  end

  def boarding_time
    (time - 1800).strftime('%l:%M%P')
  end

  def formatted_duration
    "%dh %02dm" % duration.divmod(60)
  end

  def formatted_flight_number
    reset_flight_number! unless flight_number

    "OA#{flight_number}"
  end

  def reset_flight_number!
    update(flight_number: rank)
  end

  private

  def rank
    self.class.where('date = ? AND time < ?', date, time).count + 1
  end
end

app/models/passenger.rb
# == Schema Information
#
# Table name: passengers
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  email      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Passenger < ApplicationRecord
  has_many :passenger_bookings, dependent: :delete_all
  has_many :bookings, through: :passenger_bookings, inverse_of: :passengers
  has_many :flights, through: :bookings

  validates :name, :email, presence: true
  validates :email, uniqueness: true, if: -> { !email.blank? }

  def formatted_name_long
    name.slice(0, 23).upcase
  end

  def formatted_name_short
    name.length < 16 ? name.upcase : name.slice(0, 18)
  end
end

app/models/passenger_booking.rb
# == Schema Information
#
# Table name: passenger_bookings
#
#  passenger_id :bigint           not null
#  booking_id   :bigint           not null
#
class PassengerBooking < ApplicationRecord
  belongs_to :passenger
  belongs_to :booking
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def about
    render 'shared/about'
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def new
    if params[:tickets].blank?
      flash.alert = 'You must select the number of passengers in your search in order to book a flight.'
      redirect_to root_url
    else
      @booking = Booking.new
      params[:tickets].to_i.times { @booking.passengers.build }
      @flight = Flight.find(params[:flight_id])
      render :new
    end
  end

  def create
    @booking = Booking.new(booking_params)
    if @booking.save
      flash.notice = "Flight #{@booking.flight.formatted_flight_number} successfully booked! A confirmation email has been sent to each passenger."
      PassengerMailer.with(booking_id: @booking.id).thank_you.deliver_now
      redirect_to booking_path(@booking.confirmation)
    else
      flash.now[:alert] = ''
      if @booking.errors[:'passengers.name'].include?("can't be blank") ||
         @booking.errors[:'passengers.email'].include?("can't be blank")   
        flash.now[:alert] << 'The highlighted fields cannot be left blank. '
      end
      if @booking.errors[:'passengers.email'].include?('has already been taken')
        flash.now[:alert] << 'The highlighted email address has been taken by a user with a different name.'
      end
      @flight = Flight.find(params[:booking][:flight_id])
      render :new
    end
  end

  def show
    @booking = Booking.find_by(confirmation: params[:id])
    if @booking
      render :show
    else
      flash[:alert] = 'Sorry, the booking you\'re looking for does not exist.'
      redirect_to root_url
    end
  end

  def search
    if params.has_key?(:button)
      if !params.has_key?(:search_field)
        flash.alert = 'You must select to search by Confirmation Number or Email Address.'
        redirect_to search_bookings_url
      elsif params[:search_field] == 'confirmation'
        @booking = Booking.find_by(confirmation: params[:search_param].upcase)
        if @booking
          redirect_to booking_url(@booking.confirmation)
        else
          flash.alert = 'No booking could be found with the given parameters.'
          redirect_to search_bookings_url
        end
      else
        @bookings = Booking.includes(:passengers, flight: [:origin, :destination])
                           .where('passengers.email ILIKE ?', params[:search_param])
                           .references(:passengers)
                           .order(:date, :time)
        @email = params[:search_param]
        flash.alert = 'No booking could be found with the given parameters.' if @bookings.empty?
        render :search
      end
    else
      render :search
    end
  end

  def index
    redirect_to search_bookings_url
  end

  private

  def booking_params
    params.require(:booking).permit(:flight_id, passengers_attributes: [:id, :name, :email])
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @flight = params[:flight] ? Flight.new(search_params) : Flight.new
    if params[:flight]
      # removes fields user did not select (e.g. origin: '')
      params[:flight].delete_if { |_k, v| v.empty? }
      @flights = (params[:flight].empty? ? Flight.all : Flight.where(flight_params)).includes(:origin, :destination).order(:date, :time).limit(1000)
    end
  end

  private

  # search_params is designed to build the Flight object that will populate the search params
  # on a redirect after a search (it includes :tickets which is not in the db table)

  # flight_params is used to query the database

  def flight_params
    params.require(:flight).permit(:origin_id, :destination_id, :date)
  end

  def search_params
    params.require(:flight).permit(:origin_id, :destination_id, :date, :tickets)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<h3>Complete Booking</h3>
<%= render 'flights/flight', flight: @flight %>

<h4>Passengers Details...</h4>

  <%= form_with(model: @booking, local: true) do |form| %>
    <%= form.hidden_field :flight_id, value: @flight.id %>
    <div class='passenger-form-container'>
        <%= form.fields_for :passengers do |passengers_form| %>
          <%= passengers_form.hidden_field :id, value: nil %>
          <div class='passenger-form-fields'>
            <div class='input-container'>
              <%= passengers_form.text_field :name, class: 'passenger-input no-right-border', placeholder: 'Passenger Name' %>
            </div>
            <div class='input-container'>
              <%= passengers_form.text_field :email, class: 'passenger-input', placeholder: 'Passenger Email' %>
            </div>
          </div>
        <% end %>
    </div>
    <div id='confirmation-buttons'>
      <%= link_to 'Cancel', root_path, id: 'cancel-booking' %>
      <ion-icon name="airplane-sharp", id='booking-airplane'></ion-icon>
      <%= form.submit 'Book Flight', id: 'book-flight' %>
    </div>
  <% end %>

app/views/bookings/search.html.erb
<h3>Find a booking</h3>

<%= form_with(url: search_bookings_path, method: :get, local: true) do |form| %>
  <div class='booking-search-form'>

    <%= select_tag(:search_field,
                  options_for_select([['---- Search By ----', 0], ['Confirmation Number', 'confirmation'], ['Email Address', 'email']], { disabled: 0, selected: 0 }),
                  id: 'search-booking-select'
                  ) %>

    <%= form.text_field :search_param %>

    <%= form.button :Search, id: 'search-button' %>
  </div>
<% end %>

<% if @bookings %>
  <h4>Bookings for <i><%= @email %></i></h4>
  <table>
    <thead>
      <tr>
        <th>Confirmation #</th>
        <th>Departs</th>
        <th>Arrives</th>
        <th>Departure Date</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @bookings.all.each do |booking| %>
        <tr>
          <td><%= booking.confirmation %></td>
          <td><%= booking.flight.origin.code %></td>
          <td><%= booking.flight.destination.code %></td>
          <td><%= booking.flight.formatted_date %></td>
          <td class='td-booking'>
            <%= button_to 'View Booking',
                booking_path(booking),
                method: :get,
                id: 'booking-button' %>
          </td>
        </tr>
      <% end %>
  
<% end %>

app/views/bookings/show.html.erb
<br>
<br>

<%= render 'flights/flight', flight: @booking.flight %>
<h3 id='confirmation-display'>Confirmation Number: <%= @booking.confirmation %></h3>

<div class='ticket-container'>
  <% @booking.passengers.each do |passenger| %>
    <div class='ticket'>
      <div class='logo-main logo ticket-item'>
        <ion-icon name="airplane-sharp", id='airplane-ticket-logo'></ion-icon>
        <span>Odin Air</span>
      </div>
      <div class='boarding-pass-main ticket-item'>Boarding Pass</div>
      <div class='logo-stub logo ticket-item'>
        <ion-icon name="airplane-sharp", id='airplane-ticket-logo'></ion-icon>
        <span>Odin Air</span>
      </div>
      <div class='itinerary-main ticket-item'>
        <span><%= @booking.flight.origin.code %></span>
        <ion-icon name="airplane-sharp", id='airplane-direction'></ion-icon>
        <span><%= @booking.flight.destination.code %></span>
      </div>
      <div class='passenger-stub ticket-item'>
        <div class='ticket-header'>Passenger</div>
        <div><%= passenger.formatted_name_short %></div>
      </div>
      <div class='flight-stub ticket-item stub-right'>
        <div class='ticket-header'>Flight</div>
        <div><%= @booking.flight.formatted_flight_number %></div>
      </div>
      <div class='origin-stub ticket-item'>
        <div class='ticket-header'>Origin</div>
        <div><%= @booking.flight.origin.code %></div>
      </div>
      <div class='destination-stub ticket-item stub-right'>
        <div class='ticket-header'>Destination</div>
        <div><%= @booking.flight.destination.code %></div>
      </div>
      <div class='passenger-main ticket-item'>
        <div class='ticket-header'>Passenger</div>
        <div><%= passenger.formatted_name_long %></div>
      </div>
      <div class='flight-main ticket-item'>
        <div class='ticket-header'>Flight</div>
        <div><%= @booking.flight.formatted_flight_number %></div>
      </div>
      <div class='boarding-main ticket-item'>
        <div class='ticket-header'>Boarding</div>
        <div><%= @booking.flight.boarding_time %></div>
      </div>
      <div class='departure-main ticket-item'>
        <div class='ticket-header'>Departure</div>
        <div><%= @booking.flight.formatted_time %></div>
      </div>
      <div class='boarding-stub ticket-item'>
        <div class='ticket-header'>Boarding</div>
        <div><%= @booking.flight.boarding_time %></div>
      </div>
      <div class='departure-stub ticket-item stub-right'>
        <div class='ticket-header'>Departure</div>
        <div><%= @booking.flight.formatted_time %></div>
      </div>
    </div>
  <% end %>
</div>

app/views/flights/_flight.html.erb
<table>
  <thead>
    <tr>
      <th>Flight #</th>
      <th>Departs</th>
      <th>Arrives</th>
      <th>Date</th>
      <th>Departure</th>
      <th>Duration</th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><%= flight.formatted_flight_number %></td>
      <td><%= flight.origin.code %></td>
      <td><%= flight.destination.code %></td>
      <td><%= flight.formatted_date %></td>
      <td><%= flight.formatted_time %></td>
      <td><%= flight.formatted_duration %></td>
    </tr>
  </tbody>
</table>

app/views/flights/_flights.html.erb
<% if flights %>

<h4><%= pluralize(flights.length, 'flight') %> matched your search</h4>

  <table>
    <thead>
      <tr>
        <th>Flight #</th>
        <th>Departs</th>
        <th>Arrives</th>
        <th>Date</th>
        <th>Departure</th>
        <th>Duration</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% flights.each do |flight| %>
        <tr>
          <td><%= flight.formatted_flight_number %></td>
          <td><%= flight.origin.code %></td>
          <td><%= flight.destination.code %></td>
          <td><%= flight.formatted_date %></td>
          <td><%= flight.formatted_time %></td>
          <td><%= flight.formatted_duration %></td>
          <td class='td-booking'>
            <%= button_to 'Book Flight',
                new_booking_path,
                method: :get,
                params: { flight_id: flight.id, tickets: params[:flight][:tickets] },
                id: 'booking-button' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/flights/_search_form.html.erb
<%= simple_form_for(flight, url: flights_path, method: :get, local: true) do |form| %>

  <div class="search-form">
    <%= form.collection_select(:origin_id,
                               Airport.all.order(:city),
                               :id,
                               :city, 
                               include_blank: 'Origin') %><!--
    
    --><%= form.collection_select(:destination_id,
                               Airport.all.order(:city),
                               :id,
                               :city,
                               include_blank: 'Destination') %><!--

    --><%= form.collection_select(:date,
                               Flight.select(:date).distinct.order(:date),
                               :date,
                               :formatted_date,
                               include_blank: 'Date') %><!--

    --><%= form.select(:tickets, 1..4, include_blank: 'Passengers') %><!--

    --><%= form.button :submit, 'Search', id: 'search-button' %>
  </div>

<% end %>

app/views/flights/index.html.erb
<h3>Search for flights</h3>

<%= render 'search_form', flight: @flight %>

<br>

<%= render 'flights', flights: @flights %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Odin Air</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Tangerine:wght@700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Nanum+Myeongjo:wght@400;700;800&display=swap" rel="stylesheet">
    <%= favicon_link_tag asset_path("favicon.svg") %>
  </head>

  <body>
    <header>
      <div class='header-left'>
        <button class='header-button border-right'>
          <ion-icon name="airplane-sharp"></ion-icon><%= link_to 'Odin Air', root_path, class: 'title header-item' %>
        </button><!--
        --><button class='header-button border-right'>
          <%= link_to 'Flights', flights_path, class: 'header-item' %>
        </button><!--
        --><button class='header-button border-right'>
          <%= link_to 'Bookings', search_bookings_path, class: 'header-item' %>
        </button>
      </div>
      <div class='header-right'>
        <button class='header-button border-left'>
          <%= link_to 'About', about_path, class: 'header-item' %>
        </button>
      </div>
    </header>
    <% if notice || alert %>
      <div class='flash-container'>
        <% if notice %>
          <div id="notice"><%= notice %></div>
        <% end %>
        <% if alert %>
          <div class="alert"><%= alert %></div>
        <% end %>
      </div>
    <% end %>
    <div class='page-body'>
      <%= yield %>
    </div>
    
    <script type="module" src="https://unpkg.com/ionicons@5.2.3/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule="" src="https://unpkg.com/ionicons@5.2.3/dist/ionicons/ionicons.js"></script>
  </body>
</html>

app/views/shared/about.html.erb
<br>
<br>
<p>Created by Andrew Hayhurst as part of the Odin Project <%=
  link_to 'curriculum', 'https://www.theodinproject.com/courses/ruby-on-rails/lessons/building-advanced-forms'
  %>. View on <%=
  link_to 'Github', 'https://github.com/andrewjh271/odin_flight_booker' %>.</p>
<p>Search with <i>odin@example.com</i> to view Odin's bookings.</p>

<div class='empty-space'></div>

<%= link_to 'Home', root_path, id: 'home-link' %>